nuage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('search-api/', include('search_aggregator.urls')),
    path('admin/', admin.site.urls),
]

search_aggregator/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'search_aggregator'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^result', views.result, name='result')
]

search_aggregator/models.py
from django.db import models
from enum import IntEnum, unique


@unique
class SourceType(IntEnum):
    PAYTM = 1
    SHOPCLUES = 2
    TATACLIQ = 3


ITEM_SOURCES = tuple((member.value, member.name) for _, member in SourceType.__members__.items())


# ITEM_SOURCES = (
#     (1, 'PAYTM'),
#     (2, 'SHOPCLUES'),
#     (3, 'TATACLIQ')
# )


class Product(models.Model):
    name = models.CharField(max_length=800, db_index=True)
    product_id = models.CharField(max_length=200)
    url = models.URLField(max_length=800, db_index=True, unique=True)
    image_url = models.URLField(max_length=800)
    price = models.FloatField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)
    source = models.IntegerField(choices=ITEM_SOURCES)

search_aggregator/views.py
from django.shortcuts import render

from .models import Product

from search_aggregator.service import search_paytm, search_shopclue, search_tatacliq


def index(request):
    # TODO: Use pagination and per page item here
    products = Product.objects.all()
    product_list = []
    for p in products:
        product_list.append(
            {
                "product_id": p.product_id,
                "product_name": p.name,
                "url": p.url,
                "image_url": p.image_url,
                "price": p.price
            }
        )
    context = {'product_list': product_list}
    return render(request, 'search_aggregator/index.html', context)


def result(request):
    post_data = request.POST
    search_string = post_data.get('search_string')
    # TODO: USE Threading or async in API calls
    products = search_paytm(search_string)
    products.extend(search_shopclue(search_string))
    products.extend(search_tatacliq(search_string))
    context = {'product_list': products}
    return render(request, 'search_aggregator/search_result.html', context)

search_aggregator/templates/search_aggregator/index.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      body {
        font-family: Arial;
      }

      * {
        box-sizing: border-box;
      }

      form.example input[type=text] {
        padding: 10px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 80%;
        background: #f1f1f1;
      }

      form.example button {
        float: left;
        width: 20%;
        padding: 10px;
        background: #2196F3;
        color: white;
        font-size: 17px;
        border: 1px solid grey;
        border-left: none;
        cursor: pointer;
      }

      form.example button:hover {
        background: #0b7dda;
      }

      form.example::after {
        content: "";
        clear: both;
        display: table;
      }
    </style>
  </head>

  <body>
    <form method="POST" class="example" action="/search-api/result" style="margin:auto;max-width:300px">{% csrf_token %}
      <input type="text" placeholder="Search product here" name="search_string" required="true">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    {% if product_list|length == 0 %}
      <p style=" font-size: 23px;
          line-height: 17px;
          color: #222;
          margin: 4px 0 4px 0;
          text-decoration:none !important;
          max-width: 525px;
          display: inline-block;">
        Please start product search
      </p>
    {% endif %}
    {% if product_list|length > 0 %}
      <table
        width="100%"
        cellpadding="0"
        cellspacing="0"
        style="padding:0 12px 6px 12px;
          {% if not forloop.last %}
            border-bottom: 1px solid #e8e8e8;
          {% endif %}">
        <tr>
          <td align="left">
            <div>
              <div
                style="padding:2px 0 2px 0">
                <div style="color:#737373;font-size:12px">
                  
                  {% for product in product_list %}
                    <table width="100%"
                      cellpadding="0"
                      cellspacing="0"
                      style="padding:0 12px 6px 12px;
                        {% if not forloop.last %}
                          border-bottom: 1px solid #e8e8e8;
                        {% endif %}">
                      <tr>
                        <td
                          background="{{ product.image_url }}"
                          height="60" width="100" valign="bottom"
                          style="padding:0 0 5px 0;
                                text-align:center;
                                border:1px solid #e4e4e4;
                                background: url({{ product.image_url }}) no-repeat top / cover;">
                        </td>
                        <td style="padding-right:18px"></td>
                        <td align="left">
                          
                          <a name="{{ product.product_name }}"
                             href="{{ product.url }}"
                             style="margin-top: 10px;
                             margin-right: 7px;
                             text-decoration: none;
                             line-height:20px;
                             color: #427FEF;
                             font-size: 16px;
                             word-break: break-word;
                             list-style: disc outside none;"
                             target="_blank">
                            {{ product.product_name }}
                          </a>
                          
                        </td>
                        <p style=" font-size: 13px;
                            line-height: 17px;
                            color: #222;
                            margin: 4px 0 4px 0;
                            text-decoration:none !important;
                            max-width: 525px;
                            display: inline-block;">
                            Price: {{ product.price }}
                        </p>
                      </tr>
                    </table>
                  {% endfor %}
                </div>
              </div>
            </div>
          </td>
        </tr>
      </table>
    {% endif %}

  </body>
</html>

search_aggregator/templates/search_aggregator/search_result.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
      body {
        font-family: Arial;
      }

      * {
        box-sizing: border-box;
      }

      form.example input[type=text] {
        padding: 10px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 80%;
        background: #f1f1f1;
      }

      form.example button {
        float: left;
        width: 20%;
        padding: 10px;
        background: #2196F3;
        color: white;
        font-size: 17px;
        border: 1px solid grey;
        border-left: none;
        cursor: pointer;
      }

      form.example button:hover {
        background: #0b7dda;
      }

      form.example::after {
        content: "";
        clear: both;
        display: table;
      }
    </style>
  </head>

  <body>
    <form method="POST" class="example" action="/search-api/result" style="margin:auto;max-width:300px">{% csrf_token %}
      <input type="text" placeholder="Search product here" name="search_string" required="true">
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    <a
       href="{% url 'search_aggregator:index'%}"
       style="margin-top: 10px;
       margin-right: 7px;
       text-decoration: none;
       line-height:20px;
       color: #427FEF;
       font-size: 16px;
       word-break: break-word;
       list-style: disc outside none;"
       target="_blank">
      All Products
    </a>
  
    <table
      width="100%"
      cellpadding="0"
      cellspacing="0"
      style="padding:0 12px 6px 12px;
        {% if not forloop.last %}
          border-bottom: 1px solid #e8e8e8;
        {% endif %}">
      <tr>
        <td align="left">
          <div>
            <div
              style="padding:2px 0 2px 0">
              <div style="color:#737373;font-size:12px">
                
                {% for product in product_list %}
                  <table width="100%"
                    cellpadding="0"
                    cellspacing="0"
                    style="padding:0 12px 6px 12px;
                      {% if not forloop.last %}
                        border-bottom: 1px solid #e8e8e8;
                      {% endif %}">
                    <tr>
                      <td
                        background="{{ product.image_url }}"
                        height="60" width="100" valign="bottom"
                        style="padding:0 0 5px 0;
                              text-align:center;
                              border:1px solid #e4e4e4;
                              background: url({{ product.image_url }}) no-repeat top / cover;">
                      </td>
                      <td style="padding-right:18px"></td>
                      <td align="left">
                        
                        <a name="{{ product.product_name }}"
                           href="{{ product.url }}"
                           style="margin-top: 10px;
                           margin-right: 7px;
                           text-decoration: none;
                           line-height:20px;
                           color: #427FEF;
                           font-size: 16px;
                           word-break: break-word;
                           list-style: disc outside none;"
                           target="_blank">
                          {{ product.product_name }}
                        </a>
                        
                      </td>
                      <p style=" font-size: 13px;
                          line-height: 17px;
                          color: #222;
                          margin: 4px 0 4px 0;
                          text-decoration:none !important;
                          max-width: 525px;
                          display: inline-block;">
                          Price: {{ product.price }}
                        </p>
                    </tr>
                  </table>
                {% endfor %}
              </div>
            </div>
          </div>
        </td>
      </tr>
    </table>

  </body>
</html>